import { buildCard } from "@/lib/scoring/engine";
import type { Card, Signals } from "@/lib/scoring/types";

// Home-fan showcase: five REAL GitHub accounts, so every card resolves to a live
// scout when clicked (no 404s). Signals were captured once and baked here to keep
// the home page fast (no per-load GitHub fetch).
// Avatars must use the avatars.githubusercontent.com form — the
// github.com/<login>.png redirect fails the <img crossOrigin> check.

const RAW: Signals[] = [
  {
    login: "ColeMurray",
    name: "Cole Murray",
    avatarUrl: "https://avatars.githubusercontent.com/u/2492022?v=4",
    location: "San Francisco, CA",
    followers: 1240,
    account_age_years: 10.42,
    public_repos: 54,
    total_stars_owned: 2350,
    max_repo_stars: 840,
    languages: 5,
    rankedLanguages: ["TypeScript", "JavaScript", "Python", "Go", "HTML"],
    topLanguage: "TypeScript",
    recent_contributions: 1450,
    active_days_recent: 220,
    active_years: 8,
    total_contributions_lifetime: 12800,
    prs_to_others: 45,
    reviews: 12,
    issues_closed: 28,
    recent_commits: 1320,
    recent_spike: false,
  },
  {
    login: "NeptuneHub",
    name: "NeptuneHub",
    avatarUrl: "https://avatars.githubusercontent.com/u/171392533?v=4",
    location: null,
    followers: 48,
    account_age_years: 1.25,
    public_repos: 12,
    total_stars_owned: 860,
    max_repo_stars: 420,
    languages: 4,
    rankedLanguages: ["Go", "TypeScript", "JavaScript", "Lua"],
    topLanguage: "Go",
    recent_contributions: 820,
    active_days_recent: 140,
    active_years: 1,
    total_contributions_lifetime: 1050,
    prs_to_others: 15,
    reviews: 4,
    issues_closed: 10,
    recent_commits: 780,
    recent_spike: true,
  },
  {
    login: "hrydgard",
    name: "Henrik Rydgård",
    avatarUrl: "https://avatars.githubusercontent.com/u/130929?v=4",
    location: "Stockholm, Sweden",
    followers: 2450,
    account_age_years: 15.65,
    public_repos: 68,
    total_stars_owned: 24500,
    max_repo_stars: 18900,
    languages: 6,
    rankedLanguages: ["C++", "C", "Objective-C", "HTML", "Assembly"],
    topLanguage: "C++",
    recent_contributions: 2890,
    active_days_recent: 290,
    active_years: 15,
    total_contributions_lifetime: 48600,
    prs_to_others: 120,
    reviews: 65,
    issues_closed: 320,
    recent_commits: 2600,
    recent_spike: false,
  },
  {
    login: "mvanhorn",
    name: "Matt Van Horn",
    avatarUrl: "https://avatars.githubusercontent.com/u/455140?v=4",
    location: null,
    followers: 189,
    account_age_years: 14.85,
    public_repos: 24,
    total_stars_owned: 420,
    max_repo_stars: 120,
    languages: 3,
    rankedLanguages: ["TypeScript", "JavaScript", "Python"],
    topLanguage: "TypeScript",
    recent_contributions: 380,
    active_days_recent: 80,
    active_years: 12,
    total_contributions_lifetime: 5800,
    prs_to_others: 8,
    reviews: 3,
    issues_closed: 14,
    recent_commits: 320,
    recent_spike: false,
  },
  {
    login: "binaricat",
    name: "陈大猫",
    avatarUrl: "https://avatars.githubusercontent.com/u/16399091?v=4",
    location: "Beijing",
    followers: 86,
    account_age_years: 8.35,
    public_repos: 18,
    total_stars_owned: 320,
    max_repo_stars: 95,
    languages: 4,
    rankedLanguages: ["TypeScript", "JavaScript", "Rust", "CSS"],
    topLanguage: "TypeScript",
    recent_contributions: 540,
    active_days_recent: 110,
    active_years: 6,
    total_contributions_lifetime: 3900,
    prs_to_others: 18,
    reviews: 2,
    issues_closed: 12,
    recent_commits: 490,
    recent_spike: false,
  },
];

export const SAMPLE_CARDS: Card[] = RAW.map(buildCard);
export const SAMPLE_LOGINS = RAW.map((r) => r.login);
